name: Automated Tests

on: pull_request

jobs:
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4

      - uses: actions/setup-node@4
        with:
          node-version: "lts/hydrogen"
      
      - run: npm ci
      
      - run: npm test

